### PR TITLE
Fixes use of functions with Assistant and adds an example.

### PR DESCRIPTION
**Pull request by vega113**
- Renames RequiredAction to ToolChoice
- Adds RequiredAction to receive requested tool outputs by Assistant
- Adds missing case classes for fetching required actions
- Adds submitToolOutputs to update Assistant with function output
- Adds an example of a function call with Assistant.

### CODE REVIEW

**Comment by peterbanda** [comment]
Hi @vega113 , thanks for submitting a PR. @bburdiliak pls. review

**Comment by bburdiliak** [comment]
Hey @vega113, thank you for the contribution.

try using `asSafeJson` instead of `asSafe`

**Comment by vega113** [comment]
Ok, thanks. However I can't reproduce the issue. I pulled the updates from
master and it still compiles locally.

**Comment by bburdiliak** [comment]
image

Thank you for putting effort into this.

I see the branch is behind master by 11 commits. Is the branch really updated?

**Comment by vega113** [comment]
I pushed a fix, please check

**Comment by peterbanda** [comment]
@vega113 almost here :)

`OpenAIServiceImpl.scala` isn't formatted properly!
`OpenAIChatCompletionServiceImpl.scala` isn't formatted properly!
`CreateRunWithFunctionCall.scala` isn't formatted properly!

**Comment by vega113** [comment]
Reformatted with scalafmt

**Pull request merged**
