### PR TITLE
Fix issues in CI pipeline

### LINKED ISSUE #29: CI is configured to run on main branch but repo uses master

### LINKED ISSUE #34: CI fails with no subprojects list "2.13.11" (or compatible version) in crossScalaVersions setting.

### LINKED ISSUE #35: CI fails with  Not found: type StackWalker
~~~
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/runner/work/openai-scala-client/openai-scala-client/"), "guice"):
[error]    io.cequence:openai-scala-core _2.12, _3
[error]    io.cequence:openai-scala-client _2.12, _3
[error] -- [E006] Not Found Error: /home/runner/work/openai-scala-client/openai-scala-client/openai-core/src/main/scala/io/cequence/openaiscala/StackWalkerUtil.java:8:17 
[error] 8 |  private static StackWalker walker = StackWalker.getInstance(StackWalker.Option.RETAIN_CLASS_REFERENCE);
[error]   |                 ^^^^^^^^^^^
[error]   |                 Not found: type StackWalker
[error]   |
[error]   | longer explanation available when compiling with `-explain`
[warn] one warning found
[error] one error found
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: io.cequence:openai-scala-core, io.cequence:openai-scala-client
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
[error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$71(Defaults.scala:3270)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (core / Compile / compileIncremental) Compilation failed
[error] (guice / update) Conflicting cross-version suffixes in: io.cequence:openai-scala-core, io.cequence:openai-scala-client
[error] Total time: 9 s, completed Jun 18, 2023 11:54:58 AM
~~~

### LINKED ISSUE #36: Build fails for Scala 3.2.2 with Instance not found for Json.format[LogprobsInfo]
~~~
 [error] -- Error: /home/runner/work/openai-scala-client/openai-scala-client/openai-client/src/main/scala/io/cequence/openaiscala/JsonFormats.scala:28:15 
[error] 28 |    Json.format[LogprobsInfo]
[error]    |    ^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Instance not found: play.api.libs.json.Writes[scala.collection.immutable.Seq[scala.collection.immutable.Map[String, scala.Double]]]
[error] -- Error: /home/runner/work/openai-scala-client/openai-scala-client/openai-client/src/main/scala/io/cequence/openaiscala/JsonFormats.scala:89:59 
~~~

### LINKED ISSUE #37: Build fails with Type Error for Scala 3.2.2
When building with:

~~~bash
sbt ++3.2.2 clean testWithCoverage
~~~

[error] -- [E170] Type Error: /home/sphelps/vcs/coding/openai-scala-client/openai-guice/src/main/scala/io/cequence/openaiscala/service/GuiceContainer.scala:20:60 
[error] 20 |  protected def instance[T: Manifest]: T = injector.instance[T]
[error]    |                                           ^^^^^^^^^^^^^^^^^^^^
[error]    |                                           T is not a class type
[error]    |----------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from GuiceContainer.scala:20
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from GuiceContainer.scala:20
[error]     ----------------------------------------------------------------------------
[warn] there were 5 deprecation warnings; re-run with -deprecation for details
[warn] two warnings found
[error] one error found
[warn] one warning found
[error] (guice / Compile / compileIncremental) Compilation failed
[error] Total time: 14 s, completed 18 Jun 2023, 13:59:32
~~~

### LINKED ISSUE #38: Build fails with declaration error with Scala 3.2.2
~~~
 [error] -- [E163] Declaration Error: /home/runner/work/openai-scala-client/openai-scala-client/openai-guice/src/main/scala/io/cequence/openaiscala/service/BaseOpenAIClientApp.scala:12:25 
[error] 12 |  override protected def modules: Seq[ScalaModule] = Seq(
[error]    |                         ^
[error]    |error overriding method modules in trait GuiceContainer of type => Seq[com.google.inject.Module];
[error]    |  method modules of type => Seq[net.codingwell.scalaguice.ScalaModule] has incompatible type
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[warn] one warning found
[error] one error found
[warn] one warning found
[info] done compiling
[error] (guice / Compile / compileIncremental) Compilation failed
[error] Total time: 26 s, completed Jun 18, 2023, 1:13:46 PM
~~~

### PR DESCRIPTION
**Pull request by phelps-sg**
This PR resolves outstanding issues with the CI pipeline.  This includes both issues with the CI configuration itself (fixes #29, fixes #34, fixes #35) , and also build problems encountered with Scala 3 (fixes #36, fixes #37, fixes #38).

### CODE REVIEW

**Comment by phelps-sg** [comment]
I believe the CI pipeline is now working correctly, but there seems to be a legitimate problem compiling for Scala 3.2.2- see #38.  Fixes # 34, fixes #35, fixes #36 and fixes #37.

**Comment by phelps-sg** [comment]
Fixes #38

**Comment by peterbanda** [comment]
Due to configuring and running Scalafix and Scalafmt on the entire code base there are too many conflicts to resolve. Could you perhaps extract only the relevant parts - i.e. changes in `build.sbt`and `continuous-integration.yml`? I can do it as well.

**Comment by peterbanda** [comment]
All the relevant parts are now in the master branch. Thanks @phelps-sg !

**Pull request closed without merging**
